# Generated by Django 5.1.1 on 2024-09-12 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тендера')),
                ('description', models.TextField(verbose_name='Описание тендера')),
                ('serviceType', models.CharField(choices=[('Service', 'Service'), ('Product', 'Product'), ('Construction', 'Construction')], default='Service', max_length=30, verbose_name='Тип услуги')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='CREATED', max_length=30, verbose_name='Статус тендера')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='user_app.employee', verbose_name='Создатель тендера')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='organization_app.organization', verbose_name='Организация')),
            ],
        ),
    ]
