# Generated by Django 5.1.1 on 2024-09-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenderVersion',
        ),
    ]
