# Generated by Django 5.1.1 on 2024-09-12 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_app', '0001_initial'),
        ('tender_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предложения')),
                ('description', models.TextField(verbose_name='Описание предложения')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='CREATED', max_length=30, verbose_name='Статус предложения')),
                ('approval_status', models.CharField(choices=[('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Submitted', max_length=30, verbose_name='Статус согласования')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.employee', verbose_name='Создатель')),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization_app.organization', verbose_name='Организация')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender_app.tender', verbose_name='Тендер')),
            ],
        ),
    ]
